Management
gtaEPIC/COMP229-Deskify-Frontend pull request #22
Opened 2023-11-27 17:59 UTC by Annie021

2023-11-27 19:03 UTC, gtaEPIC requested changes
#23

2023-11-27 19:08 UTC, gtaEPIC commented on src/App.js
Why are we trying to use this still for routing. index.js already has this

2023-11-27 19:08 UTC, Annie021 commented on src/App.js
I tried but app.js wasn't working

2023-11-27 19:38 UTC, gtaEPIC commented on src/components/AddTicket.js
> +        // Optionally, you can redirect or update the UI after a successful request
sus chatGPT usage ._.

2023-11-28 02:19 UTC, gtaEPIC approved these changes

2023-11-28 02:20 UTC, merged