Changes to Web Page
gtaEPIC/COMP229-Deskify-Frontend pull request #42
Opened 2023-12-11 09:31 UTC by Subhan636

I just make logo look more clear and add some space so it can look more neat (change as you want). also added footer page.

2023-12-12 02:10 UTC, gtaEPIC requested changes

2023-12-12 02:10 UTC, gtaEPIC commented on src/App.css
> +  text-align: center;
```suggestion
```
Pretty sure this is just making the page look worse. It's making things much more bubbly and mis-aligned and is just adding stuff to something that doesn't need to be changed.

2023-12-12 19:50 UTC, gtaEPIC requested changes
This is not what the issue was referring to.
Also don't use chatGPT, this should be an easy course, and if you have to use chatGPT to do your work then you should be asking for help.

2023-12-12 19:50 UTC, gtaEPIC commented on src/App.js
> +    </div>
Wrong File that this component is being applied to.
Also sus chatGPT usage.

2023-12-12 19:50 UTC, gtaEPIC commented on src/components/TicketDetails.js
This is not what #33 was requesting.
It meant to add on to the editing page, not it's own component.
Also you shouldn't be using chatGPT

2023-12-12 19:58 UTC, Subhan636 commented
I was confused about that issue so i used blackbox !!! I will change it once i am off work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Johnathan Hall ***@***.***>
Sent: Tuesday, December 12, 2023 2:50:22 PM
To: gtaEPIC/COMP229-Deskify-Frontend ***@***.***>
Cc: Mohammed Subhaan Asif Hakeem ***@***.***>; Assign ***@***.***>
Subject: Re: [gtaEPIC/COMP229-Deskify-Frontend] Added a footer (PR #42)


@gtaEPIC requested changes on this pull request.

This is not what the issue was referring to.
Also don't use chatGPT, this should be an easy course, and if you have to use chatGPT to do your work then you should be asking for help.

________________________________

In src/App.js<https://urldefense.com/v3/__https://github.com/gtaEPIC/COMP229-Deskify-Frontend/pull/42*discussion_r1424498983__;Iw!!NCntAZiCNxG7yDGH!aNNUItHUy7S73frSOB2dtxZSQJmK7lwiB7em5eVKeuvThfzanebtC7AJlEeoyKw_h-OvY6m932JOewh7hPqZUAw_tPEvVnjfGawotw$>:

> +  const ticketInfo = {
+    priority: 'High',
+    username: 'user123',
+    resolution: 'Issue resolved with update'
+  };
+
   return (
-      <div className="App">
-          <header className="App-header">
-              <img src={logo} className="App-logo" alt="logo" />
-              <p>
-                  This is a placeholder page.
-                  If you hit this page then something went wrong.
-              </p>
-              <small>Shouldn't be too shocking though</small>
-          </header>
-      </div>
+    <div className="App">
+      <header className="App-header">
+        <img src={logo} className="App-logo" alt="logo" />
+        <p>
+          This is a placeholder page.
+          If you hit this page then something went wrong.
+        </p>
+        <small>Shouldn't be too shocking though</small>
+      </header>
+
+      {/* Include the TicketDetails component */}
+      <TicketDetails
+        priority={ticketInfo.priority}
+        username={ticketInfo.username}
+        resolution={ticketInfo.resolution}
+      />
+
+      {/* Optionally, you can render ticket data here */}
+      {/* ... */}
+    </div>


Wrong File that this component is being applied to.
Also sus chatGPT usage.

________________________________

On src/components/TicketDetails.js<https://urldefense.com/v3/__https://github.com/gtaEPIC/COMP229-Deskify-Frontend/pull/42*discussion_r1424502381__;Iw!!NCntAZiCNxG7yDGH!aNNUItHUy7S73frSOB2dtxZSQJmK7lwiB7em5eVKeuvThfzanebtC7AJlEeoyKw_h-OvY6m932JOewh7hPqZUAw_tPEvVni_N6db9g$>:

This is not what #33<https://urldefense.com/v3/__https://github.com/gtaEPIC/COMP229-Deskify-Frontend/issues/33__;!!NCntAZiCNxG7yDGH!aNNUItHUy7S73frSOB2dtxZSQJmK7lwiB7em5eVKeuvThfzanebtC7AJlEeoyKw_h-OvY6m932JOewh7hPqZUAw_tPEvVnjplB1pJw$> was requesting.
It meant to add on to the editing page, not it's own component.
Also you shouldn't be using chatGPT

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/gtaEPIC/COMP229-Deskify-Frontend/pull/42*pullrequestreview-1778317578__;Iw!!NCntAZiCNxG7yDGH!aNNUItHUy7S73frSOB2dtxZSQJmK7lwiB7em5eVKeuvThfzanebtC7AJlEeoyKw_h-OvY6m932JOewh7hPqZUAw_tPEvVngn1a58vg$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/BCXAYI56F2EP7HIDF4LFN6TYJCYP5AVCNFSM6AAAAABAPN4MSKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZYGMYTONJXHA__;!!NCntAZiCNxG7yDGH!aNNUItHUy7S73frSOB2dtxZSQJmK7lwiB7em5eVKeuvThfzanebtC7AJlEeoyKw_h-OvY6m932JOewh7hPqZUAw_tPEvVngorKDxuw$>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-12-13 19:44 UTC, gtaEPIC commented
This pull request is being closed as the group has decided not to have a footer

2023-12-13 19:44 UTC, closed without merging